### ISSUE TITLE
Change header nav bar to have the titles: Tutors, Course Offerings, Time Slots, Rooms

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-f19/ucsb-tutor-scheduler#17]
* [ ] Rename nav bar elements
* [ ] Write unit tests

**Comment by lucasrelic99** [comment]
I'm working on writing unit tests for the nav header bar. So far I've created a new file HomePageTest.java and basically copied and pasted from lab06. Then I changed the unit tests to reflect my changes. However, I'm having trouble with the imports for the test file. I got some input from Tanay and am working on it now.
